branch-defaults:
  master:
    environment: memocha-dev
environment-defaults:
  memocha-dev:
    branch: null
    repository: null
global:
  application_name: memocha
  branch: null
  default_ec2_keyname: eb-2
  default_platform: Python 3.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
