# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
