# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
